default_install_hook_types: [pre-push]
default_stages: [pre-push]
repos:
  # Ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.0
    hooks:
      - id: ruff
        name: Ruff Lint
        types_or: [python, pyi, jupyter]
        args: [--fix, --config, pyproject.toml]
      - id: ruff-format
        name: Ruff Format
        types_or: [python, pyi, jupyter]
        args: [--config, pyproject.toml]
  # Stylelint.
  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v16.2.1
    hooks:
      - id: stylelint
        name: Stylelint
        additional_dependencies:
          - stylelint@16.2.1
          - stylelint-config-standard@36.0.0
        args:
          [
            --fix,
            --config,
            stylelint.config.js,
            --ignore-path,
            .stylelintignore,
          ]
  # ESLint.
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.56.0"
    hooks:
      - id: eslint
        name: ESLint
        additional_dependencies:
          - eslint@^8.56.0
          - eslint-config-airbnb-base
          - eslint-config-prettier
          - eslint-plugin-import
        args: [--fix, --config, .eslintrc.js, --ignore-path, .eslintignore]
  # Prettier.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        name: Prettier
        types_or: [css, javascript, html, json, yaml]
        args: [--config, .prettierrc, --ignore-path, .prettierignore]
